## Modelos de Machine Learnin Para el Espíritu de Servicio_ V2

Incluye todas las variables de la encuesta.


In [1]:
#Librerias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import io

In [2]:
# Semilla

random.seed(20565)

In [3]:
#Cargamos la base de datos a colab
from google.colab import files

uploaded = files.upload()

Saving BASE_MODELO_v2.xlsx to BASE_MODELO_v2.xlsx


In [4]:
#Guardamos la base de datos
import pandas as pd
data = pd.read_excel("BASE_MODELO_v2.xlsx")
data.head()

COLEG_CAT  RAZONUCM_PADRES  RAZONUCM_PROFESOR  RAZONUCM_REPUTACION  \
0          2                1                  1                    2   
1          2                3                  1                    3   
2          1                3                  3                    3   
3          1                1                  1                    2   
4          2                2                  1                    2   

   RAZONUCM_UBICACION  RAZONUCM_GASTOS  RAZONUCM_REC  RAZONUCM_RELIGION  \
0                   3                3             3                  1   
1                   3                3             3                  3   
2                   2                2             1                  3   
3                   2                2             2                  1   
4                   3                2             2                  1   

   RAZONUCM_RANKING  RAZONUCM_WEB  ...  SEDE ALUMNO  Ingreso  POSTULANTE BEA  \
0                 3             3  ...            1        1               0   
1                 3             3  ...            1        1               1   
2                 2             2  ...            1        1               0   
3                 2             2  ...            1        1               0   
4                 3             2  ...            1        1               1   

   TIPO_SELECCIÓN  PUNTAJE_PPS  RAMA_EDUCA  GRUPO_DEPEN  PROM_NUMNOTAS  \
0               1       578.50           2            0           6.05   
1               1       635.75           1            0           6.40   
2               1       726.20           1            2           6.63   
3               1       565.60           2            2           5.72   
4               1       674.10           1            2           6.67   

   PTJE_NEM  Cumplimiento_EESS  
0       631                  0  
1       702                  1  
2       750                  1  
3       564                  1  
4       758                  0  

[5 rows x 62 columns]

In [5]:
data["Cumplimiento_EESS"] = data["Cumplimiento_EESS"].astype("category")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 62 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   COLEG_CAT            970 non-null    int64   
 1   RAZONUCM_PADRES      970 non-null    int64   
 2   RAZONUCM_PROFESOR    970 non-null    int64   
 3   RAZONUCM_REPUTACION  970 non-null    int64   
 4   RAZONUCM_UBICACION   970 non-null    int64   
 5   RAZONUCM_GASTOS      970 non-null    int64   
 6   RAZONUCM_REC         970 non-null    int64   
 7   RAZONUCM_RELIGION    970 non-null    int64   
 8   RAZONUCM_RANKING     970 non-null    int64   
 9   RAZONUCM_WEB         970 non-null    int64   
 10  RAZONUCM_VISITA      970 non-null    int64   
 11  RAZONUCM_CARRERA     970 non-null    int64   
 12  RAZONUCM_AMIGOS      970 non-null    int64   
 13  EESS_Q1              970 non-null    int64   
 14  EESS_Q2              970 non-null    int64   
 15  EESS_Q3              97

In [7]:
variables_categ = ["RAZONUCM_PADRES", "RAZONUCM_PROFESOR", "RAZONUCM_REPUTACION", "RAZONUCM_UBICACION", "RAZONUCM_GASTOS", "RAZONUCM_REC",
                   "RAZONUCM_RELIGION", "RAZONUCM_RANKING", "RAZONUCM_WEB", "RAZONUCM_VISITA", "RAZONUCM_CARRERA", "RAZONUCM_AMIGOS",
                   "EESS_Q1", "EESS_Q2", "EESS_Q3", "EESS_Q4", "EESS_Q5", "EESS_Q6", "EESS_Q7", "EESS_Q8", "EESS_Q9", "EESS_Q10",
                   "INTERES_Q1", "INTERES_Q2", "INTERES_Q3", "INTERES_Q4", "INTERES_Q5", "INTERES_Q6", "INTERES_Q7", "INTERES_Q8",
                   "INTERES_Q9", "EXPECT_Q1", "EXPECT_Q2", "EXPECT_Q3", "EXPECT_Q4", "EXPECT_Q5", "INTERES_PART_Q1", "INTERES_PART_Q2",
                   "INTERES_PART_Q3", "PARTICIPACION_Q1", "PARTICIPACION_Q2", "PARTICIPACION_Q3", "CONOCIMIENTO_Q1", "CONOCIMIENTO_Q2",
                   "CONOCIMIENTO_Q3", "CONOCIMIENTO_Q4", "CONOCIMIENTO_Q5", "COLEG_CAT","CREENCIA_DIOS","RELIGION_HOGAR","FILIACION",
                   "FACULTAD", "SEDE ALUMNO", "Ingreso", "POSTULANTE BEA", "TIPO_SELECCIÓN","RAMA_EDUCA", "GRUPO_DEPEN"]
data[variables_categ] = data[variables_categ].astype("category")

In [8]:
#Nombre de Variables y estructura
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 62 columns):
 #   Column               Non-Null Count  Dtype   
---  ------               --------------  -----   
 0   COLEG_CAT            970 non-null    category
 1   RAZONUCM_PADRES      970 non-null    category
 2   RAZONUCM_PROFESOR    970 non-null    category
 3   RAZONUCM_REPUTACION  970 non-null    category
 4   RAZONUCM_UBICACION   970 non-null    category
 5   RAZONUCM_GASTOS      970 non-null    category
 6   RAZONUCM_REC         970 non-null    category
 7   RAZONUCM_RELIGION    970 non-null    category
 8   RAZONUCM_RANKING     970 non-null    category
 9   RAZONUCM_WEB         970 non-null    category
 10  RAZONUCM_VISITA      970 non-null    category
 11  RAZONUCM_CARRERA     970 non-null    category
 12  RAZONUCM_AMIGOS      970 non-null    category
 13  EESS_Q1              970 non-null    category
 14  EESS_Q2              970 non-null    category
 15  EESS_Q3              97

Preparación de la base de datos

In [9]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline

X = data.drop('Cumplimiento_EESS', axis=1)
y = data['Cumplimiento_EESS']

print(f'X shape: {X.shape}')
print(f'y shape: {y.shape}')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 12)

pipe = Pipeline([
    ('min_max_scaler', MinMaxScaler()),
    ('std_scaler', StandardScaler())
])

#X_train = pipe.fit_transform(X_train)
#X_test = pipe.transform(X_test)


X shape: (970, 61)
y shape: (970,)


Función para evaluar los modelos

In [10]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import matplotlib.pyplot as plt
import pandas as pd

def evaluate(model, X_train, X_test, y_train, y_test):
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    print("Resultados del Entrenamiento: \n===============================")
    clf_report = pd.DataFrame(classification_report(y_train, y_train_pred, output_dict=True))
    print(f"Matrix de Confusión:\n{confusion_matrix(y_train, y_train_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_train, y_train_pred):.4f}")
    print(f"Reporte de Clasificación:\n{clf_report}")

    print("Resultados de las Pruebas: \n===============================")
    clf_report = pd.DataFrame(classification_report(y_test, y_test_pred, output_dict=True))
    print(f"Matrix de Confusión:\n{confusion_matrix(y_test, y_test_pred)}")
    print(f"ACCURACY SCORE:\n{accuracy_score(y_test, y_test_pred):.4f}")
    print(f"Reporte de Clasificación:\n{clf_report}")

## RANDOM FOREST

In [11]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
evaluate(rf, X_train, X_test, y_train, y_test)

Resultados del Entrenamiento: 
Matrix de Confusión:
[[323   0]
 [  0 356]]
ACCURACY SCORE:
1.0000
Reporte de Clasificación:
               0      1  accuracy  macro avg  weighted avg
precision    1.0    1.0       1.0        1.0           1.0
recall       1.0    1.0       1.0        1.0           1.0
f1-score     1.0    1.0       1.0        1.0           1.0
support    323.0  356.0       1.0      679.0         679.0
Resultados de las Pruebas: 
Matrix de Confusión:
[[122  10]
 [ 10 149]]
ACCURACY SCORE:
0.9313
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.924242    0.937107  0.931271    0.930675      0.931271
recall       0.924242    0.937107  0.931271    0.930675      0.931271
f1-score     0.924242    0.937107  0.931271    0.930675      0.931271
support    132.000000  159.000000  0.931271  291.000000    291.000000


In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import export_graphviz
import graphviz
from IPython.display import display


print("\n=========RANDOM FOREST============")
criterion = ['gini', 'entropy']

params_grid = {
    'n_estimators': [5, 25, 50],
    'max_features': ['auto', 'sqrt'],
    'max_depth': [2, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

rf_clf = RandomForestClassifier(random_state=1) #42

rf_cv = GridSearchCV(rf_clf, params_grid, scoring="f1", cv=3, verbose=2, n_jobs=-1)

rf_cv.fit(X_train, y_train)
best_params = rf_cv.best_params_
print(f"Best parameters: {best_params}")

rf_clf = RandomForestClassifier(**best_params)
rf_clf.fit(X_train, y_train)

evaluate(rf_clf, X_train, X_test, y_train, y_test)


importancia_predictores = pd.DataFrame(
                            {'predictor': X_train.columns,
                             'importancia': rf_clf.feature_importances_}
                            )
print("Importancia de los predictores en el modelo")
print("-------------------------------------------")
importancia_predictores.sort_values('importancia', ascending=False)




=========RANDOM FOREST============
Fitting 3 folds for each of 432 candidates, totalling 1296 fits


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Best parameters: {'bootstrap': True, 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 50}
Resultados del Entrenamiento: 
Matrix de Confusión:
[[310  13]
 [ 12 344]]
ACCURACY SCORE:
0.9632
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.962733    0.963585  0.963181    0.963159      0.963180
recall       0.959752    0.966292  0.963181    0.963022      0.963181
f1-score     0.961240    0.964937  0.963181    0.963089      0.963178
support    323.000000  356.000000  0.963181  679.000000    679.000000
Resultados de las Pruebas: 
Matrix de Confusión:
[[116  16]
 [ 11 148]]
ACCURACY SCORE:
0.9072
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.913386    0.902439  0.907216    0.907912      0.907405
recall       0.878788    0.930818  0.907216    0.904803      0.907216
f1-score     0.895753    0.916409  0.907216    0.9

predictor  importancia
14           EESS_Q2     0.151508
17           EESS_Q5     0.108594
18           EESS_Q6     0.107508
19           EESS_Q7     0.088944
13           EESS_Q1     0.083629
..               ...          ...
58       GRUPO_DEPEN     0.000196
52       SEDE ALUMNO     0.000083
54    POSTULANTE BEA     0.000000
53           Ingreso     0.000000
42  PARTICIPACION_Q3     0.000000

[61 rows x 2 columns]

## XGBOOST

In [19]:
data = pd.read_excel("BASE_MODELO_v2.xlsx")
data["Cumplimiento_EESS"] = data["Cumplimiento_EESS"].astype("category")
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline

X = data.drop('Cumplimiento_EESS', axis=1)
y = data['Cumplimiento_EESS']

print(f'X shape: {X.shape}')
print(f'y shape: {y.shape}')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 12)

pipe = Pipeline([
    ('min_max_scaler', MinMaxScaler()),
    ('std_scaler', StandardScaler())
])

X shape: (970, 61)
y shape: (970,)


In [20]:
from xgboost import XGBClassifier

rf = XGBClassifier()
rf.fit(X_train, y_train)
evaluate(rf, X_train, X_test, y_train, y_test)


from sklearn.model_selection import cross_val_score

# Aplicar validación cruzada
scores = cross_val_score(rf, X_train, y_train, cv=5)

Resultados del Entrenamiento: 
Matrix de Confusión:
[[323   0]
 [  0 356]]
ACCURACY SCORE:
1.0000
Reporte de Clasificación:
               0      1  accuracy  macro avg  weighted avg
precision    1.0    1.0       1.0        1.0           1.0
recall       1.0    1.0       1.0        1.0           1.0
f1-score     1.0    1.0       1.0        1.0           1.0
support    323.0  356.0       1.0      679.0         679.0
Resultados de las Pruebas: 
Matrix de Confusión:
[[117  15]
 [  9 150]]
ACCURACY SCORE:
0.9175
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.928571    0.909091  0.917526    0.918831      0.917927
recall       0.886364    0.943396  0.917526    0.914880      0.917526
f1-score     0.906977    0.925926  0.917526    0.916451      0.917330
support    132.000000  159.000000  0.917526  291.000000    291.000000


In [22]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from IPython.display import display
import graphviz
# Definir el conjunto de parámetros a buscar
param_grid = {
    'n_estimators': [10, 50],
    'max_depth': [2, None],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.9],
    'colsample_bytree': [0.8, 0.9, 1.0]
}


clf = XGBClassifier(random_state=1) #42
grid_search = GridSearchCV(clf, param_grid, scoring='f1', cv=3, verbose=2, n_jobs=-1,error_score='raise')
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
clf = XGBClassifier(**best_params, random_state=1) #1
clf.fit(X_train, y_train)


print("\n=========XGBOOST============")
print(f"Best parameters: {best_params}")
evaluate(clf, X_train, X_test, y_train, y_test)


importancia_predictores = pd.DataFrame(
                            {'predictor': X_train.columns,
                             'importancia': clf.feature_importances_}
                            )
print("Importancia de los predictores en el modelo")
print("-------------------------------------------")
importancia_predictores.sort_values('importancia', ascending=False)

Fitting 3 folds for each of 36 candidates, totalling 108 fits

=========XGBOOST============
Best parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.2, 'max_depth': 2, 'n_estimators': 50, 'subsample': 0.9}
Resultados del Entrenamiento: 
Matrix de Confusión:
[[318   5]
 [  4 352]]
ACCURACY SCORE:
0.9867
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.987578    0.985994  0.986745    0.986786      0.986748
recall       0.984520    0.988764  0.986745    0.986642      0.986745
f1-score     0.986047    0.987377  0.986745    0.986712      0.986744
support    323.000000  356.000000  0.986745  679.000000    679.000000
Resultados de las Pruebas: 
Matrix de Confusión:
[[121  11]
 [  7 152]]
ACCURACY SCORE:
0.9381
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.945312    0.932515  0.938144    0.938914      0.938320
recall       0.916667    0.955975  0.938144    0.93632

predictor  importancia
18    EESS_Q6     0.199243
17    EESS_Q5     0.128314
14    EESS_Q2     0.076510
19    EESS_Q7     0.075338
16    EESS_Q4     0.064954
..        ...          ...
32  EXPECT_Q1     0.000000
33  EXPECT_Q2     0.000000
34  EXPECT_Q3     0.000000
36  EXPECT_Q5     0.000000
60   PTJE_NEM     0.000000

[61 rows x 2 columns]

## ÁRBOL DE DECISIÓN



In [14]:
from sklearn.tree import DecisionTreeClassifier
rf = DecisionTreeClassifier()
rf.fit(X_train, y_train)
evaluate(rf, X_train, X_test, y_train, y_test)

Resultados del Entrenamiento: 
Matrix de Confusión:
[[323   0]
 [  0 356]]
ACCURACY SCORE:
1.0000
Reporte de Clasificación:
               0      1  accuracy  macro avg  weighted avg
precision    1.0    1.0       1.0        1.0           1.0
recall       1.0    1.0       1.0        1.0           1.0
f1-score     1.0    1.0       1.0        1.0           1.0
support    323.0  356.0       1.0      679.0         679.0
Resultados de las Pruebas: 
Matrix de Confusión:
[[112  20]
 [ 19 140]]
ACCURACY SCORE:
0.8660
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.854962    0.875000  0.865979    0.864981      0.865911
recall       0.848485    0.880503  0.865979    0.864494      0.865979
f1-score     0.851711    0.877743  0.865979    0.864727      0.865935
support    132.000000  159.000000  0.865979  291.000000    291.000000


In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from IPython.display import display
import graphviz

# Definir el conjunto de parámetros a buscar
param_grid = {
    'criterion': ['gini', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}


clf = DecisionTreeClassifier(random_state=1) #42
grid_search = GridSearchCV(clf, param_grid, scoring='f1', cv=3, verbose=2, n_jobs=-1)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
clf = DecisionTreeClassifier(**best_params, random_state=1) #1
clf.fit(X_train, y_train)


# Imprimir los mejores parámetros
print("\n=========Árbol de Decisión============")
print(f"Best parameters: {best_params}")
evaluate(clf, X_train, X_test, y_train, y_test)


importancia_predictores = pd.DataFrame(
                            {'predictor': X_train.columns,
                             'importancia': clf.feature_importances_}
                            )
print("Importancia de los predictores en el modelo")
print("-------------------------------------------")
importancia_predictores.sort_values('importancia', ascending=False)

Fitting 3 folds for each of 144 candidates, totalling 432 fits

=========Árbol de Decisión============
Best parameters: {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 4, 'min_samples_split': 10, 'splitter': 'best'}
Resultados del Entrenamiento: 
Matrix de Confusión:
[[310  13]
 [ 18 338]]
ACCURACY SCORE:
0.9543
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.945122    0.962963  0.954345    0.954042      0.954476
recall       0.959752    0.949438  0.954345    0.954595      0.954345
f1-score     0.952381    0.956153  0.954345    0.954267      0.954359
support    323.000000  356.000000  0.954345  679.000000    679.000000
Resultados de las Pruebas: 
Matrix de Confusión:
[[114  18]
 [ 19 140]]
ACCURACY SCORE:
0.8729
Reporte de Clasificación:
                    0           1  accuracy   macro avg  weighted avg
precision    0.857143    0.886076  0.872852    0.871609      0.872952
recall       0.863636    0.880503

predictor  importancia
18     EESS_Q6     0.387805
14     EESS_Q2     0.133333
19     EESS_Q7     0.092035
13     EESS_Q1     0.058377
22    EESS_Q10     0.049407
..         ...          ...
31  INTERES_Q9     0.000000
32   EXPECT_Q1     0.000000
33   EXPECT_Q2     0.000000
34   EXPECT_Q3     0.000000
30  INTERES_Q8     0.000000

[61 rows x 2 columns]